"""Saber exception hierarchy."""

from saber.exceptions.base import (
    AlgorithmNotFoundError,
    ArtifactCompatibilityError,
    ArtifactIntegrityError,
    BenchmarkContractError,
    ConfigurationError,
    DatasetError,
    DatasetFingerprintMismatchError,
    DatasetValidationError,
    FeatureSchemaMismatchError,
    MetricError,
    MetricIncompatibleError,
    MetricNotFoundError,
    NonFiniteScoreError,
    OptimizationError,
    OptionalDependencyError,
    PartitionError,
    PartitionIntegrationError,
    PartitionValidationError,
    PersistenceError,
    PredictionContractError,
    PreprocessingContractError,
    SaberError,
    ValidationContractError,
)

__all__ = [
    "AlgorithmNotFoundError",
    "ArtifactCompatibilityError",
    "ArtifactIntegrityError",
    "BenchmarkContractError",
    "ConfigurationError",
    "DatasetError",
    "DatasetFingerprintMismatchError",
    "DatasetValidationError",
    "FeatureSchemaMismatchError",
    "MetricError",
    "MetricIncompatibleError",
    "MetricNotFoundError",
    "NonFiniteScoreError",
    "OptimizationError",
    "OptionalDependencyError",
    "PartitionError",
    "PartitionIntegrationError",
    "PartitionValidationError",
    "PersistenceError",
    "PredictionContractError",
    "PreprocessingContractError",
    "SaberError",
    "ValidationContractError",
]
